# GhostNet Configuration File
# Configuration principale pour le système de détection et de leurre GhostNet

# Configuration générale
general:
  name: "GhostNet"
  version: "1.0.0"
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_dir: "logs/"
  api_port: 8080
  api_host: "0.0.0.0"
  enable_ssl: true
  ssl_cert: "config/certs/server.crt"
  ssl_key: "config/certs/server.key"

# Configuration de détection
detection:
  enabled: true
  modes:
    - signature
    - anomaly
    - behavioral
  sensitivity: 0.8  # Entre 0 et 1
  sampling_rate: 5  # En secondes
  alert_threshold: 0.7
  max_false_positives: 5
  learning_period: 604800  # 7 jours en secondes
  
  # Règles de détection par signature
  signature_rules:
    - name: "SSH Brute Force"
      pattern: "Failed password for .* from .* port \\d+ ssh2"
      count: 5
      timeframe: 60  # En secondes
      severity: "high"
      action: "redirect_to_lure"
      
    - name: "SQL Injection Attempt"
      pattern: "'(\\s)*(or|OR)(\\s)+.*=.*"
      count: 1
      timeframe: 10
      severity: "critical"
      action: "redirect_to_lure"
      
    - name: "Directory Traversal"
      pattern: "\\.\\./\\.\\./.*"
      count: 1
      timeframe: 10
      severity: "high"
      action: "redirect_to_lure"
      
    - name: "Command Injection"
      pattern: "[;|&]\\s*(?:ls|cat|wget|curl|bash|sh|python|perl|ruby)\\s+"
      count: 1
      timeframe: 10
      severity: "critical"
      action: "redirect_to_lure"
      
    - name: "RCE Attempt"
      pattern: "(?:eval|system|exec|passthru|shell_exec|assert)\\s*\\(.*\\$_(?:GET|POST|COOKIE|REQUEST|SERVER|FILES)"
      count: 1
      timeframe: 10
      severity: "critical"
      action: "redirect_to_lure"
  
  # Détection par anomalie
  anomaly_detection:
    enabled: true
    baselines:
      - metric: "traffic_volume"
        period: "hourly"
        deviation_threshold: 0.3
      - metric: "request_types"
        period: "daily"
        deviation_threshold: 0.4
      - metric: "session_duration"
        period: "hourly"
        deviation_threshold: 0.5
      - metric: "geolocation"
        period: "daily"
        deviation_threshold: 0.7

# Configuration du générateur de leurres
lure_generator:
  enabled: true
  auto_update: true
  update_interval: 86400  # 24 heures en secondes
  mimicry_level: "high"  # low, medium, high
  resource_limit: 0.4  # Limite d'utilisation des ressources système (0-1)
  
  # Templates de leurres
  templates:
    - name: "default_linux_server"
      os: "ubuntu"
      version: "22.04"
      services:
        - name: "ssh"
          port: 22
          enabled: true
          vulnerabilities:
            - "CVE-2018-15473"
        - name: "http"
          port: 80
          enabled: true
          content_path: "templates/web/default"
        - name: "https"
          port: 443
          enabled: true
          content_path: "templates/web/default"
    
    - name: "windows_server"
      os: "windows"
      version: "2019"
      services:
        - name: "rdp"
          port: 3389
          enabled: true
        - name: "smb"
          port: 445
          enabled: true
          vulnerabilities:
            - "CVE-2020-0796"
    
    - name: "iot_device"
      os: "busybox"
      version: "1.3.1"
      services:
        - name: "telnet"
          port: 23
          enabled: true
          credentials:
            - username: "admin"
              password: "admin"
            - username: "root"
              password: "password"
        - name: "http"
          port: 8080
          enabled: true
          content_path: "templates/iot/router"

# Configuration du gestionnaire de réseau
network_manager:
  interfaces:
    - name: "eth0"
      role: "management"
      ip: "auto"
    - name: "eth1"
      role: "honeypot"
      ip: "auto"
      vlan: 100
  
  isolation:
    method: "network_namespace"  # network_namespace, container, vm
    allow_outbound: false
    rate_limit: "1mbps"
    
  redirection:
    enabled: true
    method: "iptables"  # iptables, nftables, pf
    target_ports: [22, 80, 443, 8080, 3389, 445]

# Configuration de l'AI Engine
ai_engine:
  enabled: true
  mode: "learning"  # learning, detection, hybrid
  models_dir: "models/"
  
  # Configuration pour l'apprentissage
  learning:
    algorithm: "random_forest"
    features:
      - "packet_size"
      - "inter_arrival_time"
      - "protocol"
      - "flags"
      - "flow_duration"
    training_interval: 86400  # 24 heures en secondes
    min_samples: 1000
    
  # Configuration pour le traitement du langage naturel
  nlp:
    enabled: true
    language_models:
      - name: "command_classifier"
        type: "transformer"
        path: "models/nlp/command_classifier"
      - name: "intent_recognizer"
        type: "lstm"
        path: "models/nlp/intent_recognizer"

# Configuration des alertes et des rapports
reporting:
  alerts:
    enabled: true
    methods:
      - type: "email"
        recipients: ["admin@example.com"]
        severity_threshold: "high"
      - type: "syslog"
        server: "localhost"
        port: 514
        facility: "local0"
        severity_threshold: "medium"
      - type: "webhook"
        url: "https://example.com/security/webhook"
        severity_threshold: "critical"
        
  dashboard:
    enabled: true
    update_interval: 5  # En secondes
    retention_period: 30  # En jours
    
  reports:
    daily:
      enabled: true
      time: "00:00"
      format: "pdf"
    weekly:
      enabled: true
      day: "sunday"
      time: "00:00"
      format: "pdf"
    monthly:
      enabled: true
      day: 1
      time: "00:00"
      format: "pdf"

# Intégration avec d'autres systèmes
integrations:
  siem:
    enabled: false
    type: "elastic"
    host: "localhost"
    port: 9200
    index: "ghostnet"
    username: "elastic"
    password: "password"
    
  threat_intelligence:
    enabled: true
    sources:
      - name: "alienvault"
        api_key: "your_api_key"
        refresh_interval: 86400
      - name: "virustotal"
        api_key: "your_api_key"
        refresh_interval: 86400

# Configuration de la persistance des données
storage:
  engine: "sqlite"  # sqlite, mysql, postgresql
  path: "data/ghostnet.db"
  retention_period: 90  # jours
  backup:
    enabled: true
    interval: 86400  # 24 heures en secondes
    location: "data/backups/"
    keep_last: 7  # nombre de sauvegardes à conserver
